version: 2.1

references:
  # Docker Image Config
  docker_img: &docker_img
    docker:
      - image: cimg/node:16.14.2

jobs:
  checkout_source:
    <<: *docker_img
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
    resource_class: large

  build:
    <<: *docker_img
    steps:
      - checkout
      - restore_cache:
          key: CircleCI-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: 'sudo npm i -g npm'
      - run:
          name: Install Dependencies
          command: 'yarn install'
      - save_cache:
          key: CircleCI-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
            - ~/.cache
      - run:
          name: Lint
          command: "yarn lint"
      - run:
          name: Prettier Check
          command: "yarn prettier:check"
      - run:
          name: Compile contracts
          command: "npx hardhat compile"
      - run:
          name: Test Only
          command: "yarn test:dotonly"
      - run:
          name: Test
          command: "yarn test"

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
